### ISSUE TITLE
Sprint 2 (ends 2018-08-31)

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/pre-assembly#116]
### primary goals

- [x] async environment setup (get redis etc up and running) (#79)
- [x] toward a working rails app
  - [x] abstract out yml parsing and config validation to a model (#77)
  - [x] stop hardcoding paths for file mounts (#81)
  - [x] shared_configs; figure out remaining initialization issues for rails app (#68)
- [x] find and remove unnecessary `require` statements (#83)
- [ ] determine log file location for user job output (#78)
- [x] start setting up the front end (#84)

### stretch / next week

- [ ] try to run some pre-assembly stuff via a worker.  even if invoking via worker isn't working fully, we want to prove to ourselves that it's possible in principle. (#85)

**Comment by jmartin-sul** [comment]
moved open tasks to #166.  closing this.
