### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by edsu** [sul-dlss/pre-assembly#1221]
The README.md will need to be updated:

- [x] to reflect the new file manifest format #1197 
- [x] are we still using `descMetadata.xml`?

Some Wiki pages (linked as help pages from the app) will need updating as well:

- [x] https://github.com/sul-dlss/pre-assembly/wiki/Content-Staging will need to reflect the addition of Globus as a transfer mechanism #835 
- [x] https://github.com/sul-dlss/pre-assembly/wiki/After-Accessioning will need to reflect the new states and notifications work done in #1181 
- [x] we will need a new page for targeted file updates and file manifests #1194
- [x] https://github.com/sul-dlss/pre-assembly/wiki/Explanation-of-possible-errors-in-a-discovery-report will need updates based on #1185 #1186 
- [x] ~~https://github.com/sul-dlss/pre-assembly/wiki/Discovery-Report-and-Accessioning will need updating if work #1212 is completed~~

**Comment by mjgiarlo** [comment]
Feel free to pick off part of what's described above---just make sure to ticket what remains to be done and put it in ready.

**Comment by edsu** [comment]
Going to put this on pause until we are nearer the end, to do restructuring of wiki in consultation with @andrewjbtw

**Comment by andrewjbtw** [comment]
Just noticed this ticket is still open. I finished the documentation updates towards the end of October.
