### ISSUE TITLE
Sprint 3 (ends 2018-09-07)

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/pre-assembly#166]
## overarching goals
* get plumbing setup (flesh out the classes we have, create the classes we need, start wiring)
* get rails app working on the VMs
* _Documentation!_

### primary goals
- [x] create the schema and active record models (#141, #171, #172, #175)
  - [ ] fit current `BundleContext` validation into an ActiveRecord-usable approach (i.e. switch to using individual ActiveRecord validations instead of one monolithic validation method, but validate use the same validation logic at an individual parameter level, for the params we want to keep) (#176)
  - [ ] paring down unnecessary logic and fields (#133 etc)
    * do whatever we need to to make implementation easier/faster
- [ ] job scaffolding (#126, #127)
- [x] better testing, so we can see whether we're keeping stuff working while everything is in flux (#181)
- [ ] monitoring
  - [ ] ok comuter
  - [ ] nagios
  - [ ] honeybadger
- [ ] user input, app output
  - [ ] determine log file location for user job output (#78)
  - [ ] determine where output goes, how user gets it (#161)
- [ ] ops stuff
  - [x] setup postgres (#153)
  - [x] certs for prod and stage (#155)
  - [x] ksu on stage (#160)
  - [x] ksu on prod (#189)
  - [ ] put VMs behind VPN (#153)
- [ ] wired up and running
  - [ ] done-ish: run pre-assembly and discovery report from console, figure out what we need to call to invoke it from a worker (#165, #174)
  - [ ] try to run some pre-assembly stuff via a worker.  even if invoking via worker isn't working fully, we want to prove to ourselves that it's possible in principle. (#85)
  - [ ] controllers (#186)
  - [ ] templates

### stretch / next week

- [ ] docs
  - [ ] correct old docs
  - [ ] create new ones as needed
  - [ ] `TEMPLATE.yml`, test fixtures (removal and consolidation since there are less fields to distinguish them)
- [ ] ship it!

**Comment by jmartin-sul** [comment]
carried open tasks over to #217, closing this one
