### ISSUE TITLE
Sprint 4 (ends 2018-09-14)

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/pre-assembly#217]
## overarching themes

* if we had to concentrate on one thing, get discovery report up and running, but ben says up to the team as to what's most efficient to get everything working
* trying to get something runnable from the UI for initial manual testing
* _Documentation!_

### primary goals

- [x] active record model implementation
  - [x] finish: fit current `BundleContext` validation into an ActiveRecord-usable approach (i.e. switch to using individual ActiveRecord validations instead of one monolithic validation method, but validate use the same validation logic at an individual parameter level, for the params we want to keep) (#176)
  - [x] finish: paring down unnecessary logic and fields (#133 etc)
    * do whatever we need to to make implementation easier/faster
  - [x] job history (#175)
- [x] job scaffolding:  create discovery report worker (#127)
- [x] redis config (#210)
- [ ] user input, app output (#225)
  - [ ] determine log file location for user job output (#78)
  - [ ] determine where output goes, how user gets it (#161)
  - [ ] ActiveJob should send Email (#139)
- [ ] wired up and running
  - [x] run pre-assembly from console, figure out what we need to call to invoke it from a worker (#165)
  - [x] run discovery report from console, figure out what we need to call to invoke it from a worker (#174)
  - [ ] controllers (#186)
- [ ] monitoring
  - [ ] ok computer (#283)
  - [ ] nagios (#284)
  - [x] honeybadger (PR ~~#216~~#223)
- [x] ops stuff
  - [x] put VMs behind VPN (#153)
  - [x] client certs to talk to fedora (#214)

### stretch / next week

- [ ] docs
  - [ ] correct old docs
  - [ ] create new ones as needed
  - [ ] `TEMPLATE.yml`, test fixtures (removal and consolidation since there are less fields to distinguish them)
- [ ] specs
  - [ ] fixture cleanup (#218)

### streeeeetch / unlikely
- [ ] ship it!

**Comment by jmartin-sul** [comment]
remaining issues moved to #287, closing this
