### ISSUE TITLE
Sprint 5 (ends 2018-09-21)

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/pre-assembly#287]
### TODO

_(inaccurate estimates for remaining work on the side)_

- [ ] login  _(bad estimate:  < 1 day)_
  - [x] finish setting up devise (#234)
  - [ ] workgroup setup, quick manual webauth test (#86)
- [ ] UI  _(bad estimate: 2 days, 1 or two ppl, 1 or 2 "pair person days")_
  - [x] discovery report template (#236)
  - [x] need toggle for job type in form, pass value to controller (#299)
  - [ ] simple view for job run (#295)
- [ ] user input, app output (#225)  _(bad estimate: 2 days, 1 or two ppl, 1 or 2 "pair person days")_
  - [ ] determine log file location for user job output (#78)
  - [ ] determine where output goes, how user gets it (#161)
- [ ] wiring/integration of components _(3+ pair person days)_
  - [ ] code that does work connected to workers (#85, #267)
    - [ ] update job run upon completion of work
  - [x] ActiveJob should send Email (#139)
- [ ] monitoring _(2 person days (implementation and review))_
  - [ ] ok computer (~~#283,~~ #339)
  - [ ] nagios (#284)
- [ ] docs _(3 person days)_
  - [ ]  README.md (for devs) (#260)
  - [ ] DevOpsDocs
  - [ ] usage documentation (for end users)
- [ ] testing _(1+ person weeks from completion of testable work)_
  - [ ] acceptance testing (#296)

### unlikely to make it

most of the `factoring` tickets in the backlog.
- UI
  - [ ] Refactor history partials to use JobRun AR (#293)  _(nice to have, not in estimate)_

- [ ] testing 
  - [ ] discovery report error collection and aggregation tests (#297, #298)
  - [ ] finish fixture cleanup (#218)

**Comment by jmartin-sul** [comment]
moving WIP and TODO to #342, closing this
