### ISSUE TITLE
Sprint 6: (ends 2018-09-28)

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/pre-assembly#342]
### TODO

_(inaccurate estimates for remaining work on the side)_

- [x] login (#86)  _(bad estimate:  < 1 hr of testing if it's working, half a day if not)_
  - _may already be working, need to test manually on prod_
  - [x] workgroup setup, quick manual webauth test (sul-dlss/operations-tasks#1744)
  - [x] make sure the appropriate users are listed in the appropriate workgroups (#129)
- [ ] UI  _(bad estimate: 2 pair person days, plus PO decision making)_
  - [ ] bundle context resumption/unique project name quagmire (#374)
    -  prob need a BC show view
  - [x] simple view for job run (#295)
    - [x] route for download of output (#363, #259)
    - [x] UI indicating whether job is done or not (and disabling download button if it isn't) (#363)
- [x] user input, app output (#225)   _(2.5+ pair person days)_
  - [x] wiring/integration of components
    - [x] code that does work connected to workers (#85, #345)
      - [x] discovery (#345)
      - [x] pre-assembly (#85)
        - [x] what does pre-assembly output?  (to the user, metadata artifacts for pipeline, etc)  (#349)
          - [x] determine log file location for user job output (#78)
          - [x] determine where output goes, how user gets it (#161)
          - questions:  how do we indicate status (in queue/done)?  how do we give output, esp partial failure of a pre-assembly job?  much of the progress info that was previously in prod app log is no longer useful in that place in a multi-user web app.  do we have an output log for job that the user can view, parallel to discovery report and progress log?  presence of that log in job run table might indicate pre-assembly job is done?  should merge these open questions into above tickets about questions and implementation.
- [ ] docs _(3 person days)_
  - [ ]  README.md (for devs) (#260)
  - [ ] DevOpsDocs (#304)
  - [ ] usage documentation (for end users) (#305)
- [ ] monitoring _(1 person days (implementation and review))_
  - [ ] ok computer (more than the super basic checks) (#339)
  - [ ] nagios (#284)
- [ ] testing _(1+ person weeks from completion of testable work)_
  - [x] confirm we an run smpl manifest through discovery and preassembly (#322)
  - [ ] acceptance testing (#296)

### unlikely to make it

most of the `factoring` tickets in the backlog.
- UI
  - [x] Refactor history partials to use JobRun AR (#293)  _(nice to have, not in estimate)_

- [ ] testing 
  - [ ] discovery report error collection and aggregation tests (#297, #298)
  - [x] finish fixture cleanup (#218)

**Comment by jmartin-sul** [comment]
moved open tasks to #377, closing this
