### ISSUE TITLE
re-use of existing BundleContext and project, resumption of pre-assembly work

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/pre-assembly#374]
#### some context

the purpose of `progress_log_file.yml` is to allow a partially completed pre-assembly run to continue from where it left off.  but in the new web app version of pre-assembly, it is not actually possible at the moment to use an existing progress log file.  this is because:
* the progress log file is put into the directory for a given `BundleContext` instance for a user.  the `BundleContext` dir is of the format `"#{sunet_id}/#{project_name}"`.
* when creating a new `BundleContext` instance to run a discovery report or a pre-assembly job, the code will throw an error if a project name is re-used:  that is, it expects the directory for the `BundleContext` to not be there before the `BC` is created.
* there is no way to pull up an existing `BC` instance and start a new discovery report run or pre-assembly job from it.

and thus, there is no way through the web UI to pick up where things left off with an existing progress log.

#### TODO

ideally, we would allow resumption from the web UI.  this would involve:
- [ ] an index page listing the existing `BundleContext` instances (#398)
- [x] a show page that would display a non-editable version of an existing `BundleContext`
  - [x] the show page should have buttons allowing the user to run a discovery report or to run a pre-assembly job, using that `BC` instance.
  - [ ] the show page should explain that the job will read the existing progress log file, and will only operate on the objects that haven't completed.  or maybe this gets captured by user training and documentation? (#305)
    * this implies that if the discovery report is run after a partially completed pre-assembly job, the discovery report will only run over the remaining objects, because it skips completed entries using the same progress log as pre-assembly. (related: #352)

the resumption implementation on the back-end would be that a new `JobRun` of the desired type (discovery or pre-assembly) would be created, referring to the existing `BundleContext` that the user pulled up.

#### no longer applicable because we're implementing the web UI part

alternatively, if the above is too much to implement in the limited time we have left, @atz pointed out that we could do the same manually from the rails console as follows:
* a `JobRun` instance could be created by hand on the rails console by a power user like @blalbrit or @peetucket (but not a regular user of the pre-assembly web app, since the goal of that app is to _not_ expand command-line access to a larger audience).
  * the new `JobRun` would refer to the existing `BundleContext` record with the desired progress log.
* ~~the newly created `JobRun` could then be passed to a new `PreassemblyJob` or `DiscoveryReportJob` instance as desired, and then the console user could call `#perform_later` on the new job instance.~~ actually i think the AR hooks will queue the job once the `JobRun` is created, automagically ✨ 

so, a lower cost implementation for the development team would be to just document that process.

whichever path we choose, i think part of the user education should be to point out that discovery report should be run first on the input bundle, and that pre-assembly should only be run once the report comes back clean.

#### done, see #376 

also, regardless of what happens with this ticket, we may want to add a constraint that the project name and sunetid combination should be unique across all `BundleContext` instances (both an AR validation and a DB constraint?).  separate ticket?

#### not worrying about this for now

one final question along these lines, also possibly a separate ticket:  should re-using the same input dir for pre-assembly be allowed for a new bundle?  or should input dir be unique?  i'm inclined to pass on this constraint, since an input dir may be deleted, and then the same name might get used again later?  i dunno, real world usage advice from @blalbrit or @peetucket?

see also #357, #352

**Comment by atz** [comment]
Resumption of an existing `JobRun` is easier than that.
```ruby
job_run = JobRun.find(id)
job_run.enqueue!
```
Or if you want a different row to track the job execution:
```
job_run.dup.save!
```
You are correct that a newly created `JobRun` will enqueue itself (as in the latter line).

**Comment by jmartin-sul** [comment]
closing this in favor of #398 and #305, which capture the remaining work described in this ticket
