### ISSUE TITLE
Sprint 7 (ends 2018-10-05)

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/pre-assembly#377]
### TODO

_(inaccurate estimates for remaining work on the side)_

- [ ] UI  _(bad estimate: 2 pair person days)_
  - [ ] bundle context re-use/pre-assembly job resumption (#374)
    - [x] bundle context show page (#390)
    - [x] buttons for bundle context reuse, and corresponding backend (#397)
    - [x] bundle context index page (#398)
  - [x] Default to discovery report on form (#382)
  - ~~[ ] email usability enhancments (#318)~~
- [ ] docs _(3 person days)_
  - [ ]  README.md (for devs) (#260)
  - [ ] DevOpsDocs (#304)
  - [ ] usage documentation (for end users) (#305)
- [x] security, config, etc
  - [x] restrict allowable paths for bundle input dir (#387)
- [x] auth, users, etc
  - [x] straighten out email/sunet_id usage in tests (#389)
- ~~[ ] jobs, worker setup, etc~~
  - ~~[ ] resque lock: configure such that only one thing happens with a bundle context at a time (#352)~~
- [ ] monitoring _(1 person day (implementation and review))_
  - [x] ok computer (more than the super basic checks) (#339)
  - [ ] nagios (#284)
- [x] disposition remaining TODO and FIXME statements (#355)
- [ ] testing _(1+ person weeks from completion of testable work)_
  - [ ] acceptance testing (#296)

### stretch
- [ ] discovery report presentation in GUI (#257)

### unlikely to make it

- [ ] most of the `factoring` tickets in the backlog.
- [ ] testing 
  - [ ] discovery report error collection and aggregation tests (#297, #298)

**Comment by jmartin-sul** [comment]
moving remainder over to #409, will close this once that's fleshed out

**Comment by jmartin-sul** [comment]
all the pre-assembly stuff that needs moving has been moved, so closing this.  rest of fleshing out on #409 is probably all preservation.
