### ISSUE TITLE
Sprint 1 (ends 2018-08-24)

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/pre-assembly#76]
### primary goals

- [x] vet application for amenability to being called from resque workers (#80)
- [ ] async environment setup (get redis etc up and running) (#79)
- [x] make the app deployable as a rails app on its own box, without other cohabiting apps (#82)
  - [x] make sure other apps aren't required to co-exist on the same VM for pre-assembly to work (#87)
  - [ ] abstract out yml parsing and config validation to a model (#77)
  - [ ] allowing shared configs use to coexist with current command line config use (#68, #73)
  - [ ] stop hardcoding paths for file mounts (#81)
- [ ] find and remove unnecessary `require` statements (#83)
- [ ] figure out log file location for web app (#78)
- [ ] start setting up the front end (#84)

### stretch / next week

- [ ] try to run some pre-assembly stuff via a worker.  even if invoking via worker isn't working fully, we want to prove to ourselves that it's possible in principle. (#85)

### high priority bugs
- [x] want to compare all checksums, not just last checksum (#69)

**Comment by jmartin-sul** [comment]
closed, carried over unfinished tasks to #116
