### ISSUE TITLE
confirm that webauth/shib stuff is setup properly

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/pre-assembly#86]
- [x] create the workgroup (#123)
- [x] make sure VM is setup to be webauth-aware (https://github.com/sul-dlss/operations-tasks/issues/1744)
- [x] make sure the appropriate users are listed in the appropriate workgroups (#129)
- [ ] the containing workgroup should also have the appropriate permissions in argo, so that we can use that workgroup (on its own or via an APO listing) to determine whether an argo user gets a link to the pre-assembly app (e.g. the workgroup that gives pre-assembly web app access is contained in the master argo workgroup, and is also listed in an APO that grants some particular argo role, e.g. dor-admin, or maybe something more restricted than that argo super user role).

**Comment by jmartin-sul** [comment]
make sure that webauth properly gates access to the VM.  this is just a manual test, since that all happens before the request reaches the pre-assembly app.

**Comment by SaravShah** [comment]
https://workgroup.stanford.edu/main/WGApp to view the `sdr:accessioning` workgroup. I didn't see Astrid U. name on it, so i asked her to visit : https://sul-preassembly-stage.stanford.edu/ ..... she was able to visit it fine. Meaning   (sul-dlss/operations-tasks#1744) still needs to be done.

**Comment by jmartin-sul** [comment]
@kamchan set this up on thursday.  need to do a manual test on prod with someone who *shouldn't* have access.  if that's all good, can check the setup box.  this is done when the actual correct users are added to the right workgroup.

**Comment by jmartin-sul** [comment]
punting on the last bullet point in the description, since we're not going to link out from argo to pre-assembly web app.

closing since that covers everything we plan to do under this issue.
