### ISSUE TITLE
EPIC: preassembly improvements

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/pre-assembly#918]
Areas of focus:

- [ ] Discovery Report Improvements
    - [ ] very large batches too slow (e.g. Newspaper collections), #908
    - [ ] able to restart from failure point (assuming very large batches don't become blazingly fast) #532, #717
    - [ ] able to view progress (in UI?) while job is running #257, #695, #535, #816
    - [ ] improve results output #917
- [ ] Job run result reporting

**Comment by ndushay** [comment]
calling this done.
