### ISSUE TITLE
EPIC: SDR migration carryover

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/pre-assembly#919]
- [x] Display name mapping 
    - [x] https://github.com/sul-dlss/cocina-models/issues/479 
- [x] Registration Form
    - [x] https://github.com/sul-dlss/argo/issues/3610 use html form without grid
    - [x] https://github.com/sul-dlss/argo/issues/3611 upload csv
- [x] Avoid updating desc metadata when object is closed
    - [x] https://github.com/sul-dlss/argo/issues/3706

**Comment by ndushay** [comment]
Andrew - can this epic on SDR migration carryover be closed?   I think the continuing work is getting ticketed separately.

**Comment by andrewjbtw** [comment]
Yes, closing.
