### ISSUE TITLE
Create new feature specs to test "completed with errors" AND "failed" for discovery report AND preassembly run

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/pre-assembly#942]
After work is done in #944, .... basically verify that if a discovery report fails because a bad header was added, it should go into an error state and give a message to the user with a new spec.

We need feature tests so we don't rely on Andrew testing manually in stage as much as we do now. Ideally these could be feature tests within the app.

- [x] ~~discovery report fails~~ (PR #990)
- [x] ~~discovery report completes with error (batch should have at least 1 success and 1 failed object)~~ (PR #990)
- [x] ~~preassembly run fails (PR #992)~~
- [x] ~~preassembly run completes with error  (batch should have at least 1 success and 1 failed object)~~ (PR #997)

**Comment by ndushay** [comment]
We need feature tests, if possible, so we don't rely on Andrew testing manually in stage as much as we do now.  Ideally these could be feature tests within the app.
